# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd = {
    availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
    kernelModules = ["dm-snapshot" "amdgpu"];
    luks = {
      devices.encrypted = {
        device = "/dev/nvme0n1p1";
        preLVM = true;
      };
    };
  };

  boot.tmp = {
    useTmpfs = true;
    cleanOnBoot = true;
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [
    "amdgpu.abmlevel=0"
    "amdgpu.gttsize=102400"
  ];

  boot.kernelModules = [ ];
  boot.extraModulePackages = [];
  boot.blacklistedKernelModules = ["hid_sensor_hub"];
  boot.plymouth = {enable = true;};

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/07AA-92C2";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/cf218b64-aeb2-4d26-aa05-0603e21acd81";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;

  services.pipewire.wireplumber.extraConfig.no-ucm = {
    "monitor.alsa.properties" = {
      "alsa.use-ucm" = false;
    };
  };
}
