# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd = {
    availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
    kernelModules = ["dm-snapshot"];
    luks = {
      devices.encrypted = {
        device = "/dev/nvme0n1p1";
        preLVM = true;
      };
    };
  };

  boot.tmp = {
    useTmpfs = true;
    cleanOnBoot = true;
  };

  # boot.kernelPackages = pkgs.linuxPackages_6_12;
  boot.kernelPackages = pkgs.linuxPackages_latest;
  # boot.kernelPackages = pkgs.linuxPackages_latest.extend (lpFinal: lpPrev: {
  #   cpupower = lpPrev.cpupower.overrideAttrs (old: {
  #     nativeBuildInputs = (old.nativeBuildInputs or []) ++ [ pkgs.which ];
  #     makeFlags = (old.makeFlags or []) ++ [ "INSTALL_NO_TRANSLATIONS=1" ];
  #   });
  # });
  boot.kernelParams = [
    "amdgpu.abmlevel=0"
    "amdgpu.gttsize=102400"
    "amdgpu.sg_display=0" # Fix black screen on resume
    "amdgpu.mes=0" # Fix MES failed to respond/GPU hang on resume
    # Fix mes_kiq timeout/GPU hang on resume: https://github.com/ROCm/ROCm/issues/5724
    # "amdgpu.cwsr_enable=0"
    "amdgpu.dcdebugmask=0x10" # Disable PSR, use if experiencing screen stutter or flicker
  ];

  boot.kernelModules = [ ];
  boot.extraModulePackages = [];
  boot.blacklistedKernelModules = ["hid_sensor_hub"];
  boot.plymouth = {enable = true;};

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/07AA-92C2";
    fsType = "vfat";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/cf218b64-aeb2-4d26-aa05-0603e21acd81";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  services.pipewire.wireplumber.extraConfig.no-ucm = {
    "monitor.alsa.properties" = {
      "alsa.use-ucm" = false;
    };
  };
}
