# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd = {
    availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "sd_mod"
    ];
    kernelModules = [
      "dm-snapshot"
      "amdgpu"
    ];
    luks = {
      devices.encrypted = {
        device = "/dev/nvme0n1p1";
        preLVM = true;
      };
    };
  };

  boot.tmp = {
    useTmpfs = true;
    cleanOnBoot = true;
  };

  boot.kernelPackages = pkgs.linuxPackages_latest;

  # ttm.pages_limit / ttm.page_pool_size are raised to 100 GiB (26214400 * 4 KiB)
  # on purpose: running LLMs on the iGPU needs model weights resident in GTT, far
  # past the default cap. These are deliberate — don't "tidy" them away.
  #
  # amdgpu.gttsize=102400 (also 100 GiB) used to sit here too, but the kernel
  # deprecates it: "Configuring gttsize via module parameter is deprecated, please
  # use ttm.pages_limit". With gttsize unset, amdgpu derives GTT size from
  # ttm.pages_limit, which already asks for the same 100 GiB — so it was redundant,
  # not load-bearing. Verify after a rebuild that dmesg still reports
  # "102400M of GTT memory ready".
  boot.kernelParams = [
    "amdgpu.abmlevel=0"
    "amdgpu.dcdebugmask=0x40410"
    "ttm.pages_limit=26214400"
    "ttm.page_pool_size=26214400"
  ];

  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "hid_sensor_hub" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3ab7175e-f003-48bc-bbdb-26d94e17695d";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/07AA-92C2";
    fsType = "vfat";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/4e4839b8-9c9f-4499-85de-5e0bf952b11a"; } ];

  # Same device as swapDevices above. This is NOT redundant: with a systemd
  # initrd (boot.initrd.systemd.enable), nixpkgs emits `resume=` on the kernel
  # cmdline only from boot.resumeDevice — there is no swapDevices fallback like
  # the scripted initrd has (NixOS/nixpkgs#273053). Without it, resume depends
  # entirely on the volatile EFI HibernateLocation variable, and a lost variable
  # means a cold boot with the session gone. Also raises the resume job timeout
  # from 2 minutes to infinity.
  boot.resumeDevice = "/dev/disk/by-uuid/4e4839b8-9c9f-4499-85de-5e0bf952b11a";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  hardware.enableRedistributableFirmware = true;

  services.pipewire.wireplumber.extraConfig.no-ucm = {
    "monitor.alsa.properties" = {
      "alsa.use-ucm" = false;
    };
  };
}
